version: "3"
services:
  efiss-ai:
    build:
      context: .
      dockerfile: searcher/Dockerfile.cuda
    image: efiss-ai:latest-cuda
    container_name: efiss-ai
    restart: on-failure
    networks:
      - efiss
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  efiss:
    driver: bridge
