version: '3.9'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "58483:58483"
    volumes:
      - /media/thaiminhpv/DataStorage/EFISS/jobs/:/app/uploads/
